# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 23:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved',
            name='solved_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 23, 38, 25, 328517, tzinfo=utc), verbose_name='solved time'),
        ),
    ]
