# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 00:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160411_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='classroom',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='lab',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='solved',
            name='solved_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 0, 32, 23, 101214, tzinfo=utc), verbose_name='solved time'),
        ),
    ]
