# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 00:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160411_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='classroom',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='lab',
        ),
        migrations.AlterField(
            model_name='solved',
            name='solved_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 0, 33, 46, 492631, tzinfo=utc), verbose_name='solved time'),
        ),
    ]
