# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160412_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solved',
            name='solved_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 23, 28, 5, 180122, tzinfo=utc), verbose_name='solved time'),
        ),
    ]
