# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160412_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solved',
            name='solved_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='solved time'),
        ),
    ]
