# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160412_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField(default=datetime.datetime(2016, 4, 25, 0, 4, 28, 676006, tzinfo=utc), verbose_name='due date')),
                ('problems', models.ManyToManyField(to='app.Problem')),
            ],
        ),
    ]
