# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='question',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 9, 15, 23, 21, 167223, tzinfo=utc), verbose_name='due date'),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
