# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 14:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160501_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 11, 14, 53, 11, 980357, tzinfo=utc), verbose_name='due date'),
        ),
    ]
