# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160501_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='compiles_to',
            new_name='evalutes_to',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 13, 22, 5, 33, 838966, tzinfo=utc), verbose_name='due date'),
        ),
    ]
