# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160501_0953'),
    ]

    operations = [

        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 11, 18, 36, 12, 693146, tzinfo=utc), verbose_name='due date'),
        ),
    ]
