# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160503_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 20, 17, 4, 41, 558542, tzinfo=utc), verbose_name='due date'),
        ),
    ]
