# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160503_1705'),
        ('app', '0017_auto_20160501_1403'),
    ]

    operations = [
    ]
