# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 14, 16, 41, 48, 327372, tzinfo=utc), verbose_name='due date'),
        ),
    ]
