# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20160509_1659'),
        ('app', '0016_auto_20160510_1204'),
    ]

    operations = [
    ]
